tests/test-run.c: Comment out unused variable
test-run.c: In function ‘read_tests’:
test-run.c:132:9: error: variable ‘lc’ set but not used [-Werror=unused-but-set-variable=]
  132 |     int lc = 0;
      |         ^~