acinclude.m4: Disable -Winline warnings
GCC 14.2.1 gives warnings like:

In file included from memory.h:26,
                 from augmatch.c:30:
In function ‘guess_lens_name’,
    inlined from ‘main’ at augmatch.c:396:16:
internal.h:229:19: error: inlining failed in call to ‘streqv’: call is unlikely and code size would grow [-Werror=inline]
  229 | static inline int streqv(const char *a, const char *b) {
      |                   ^~~~~~
augmatch.c:294:9: note: called from here
  294 |     if (streqv(ext, ".json")) {
      |         ^~~~~~~~~~~~~~~~~~~~

These warnings don't seem very useful in Augeas, since we are not so
sensitive to code size and don't care about inlining "purity".  Rather
than attempting to "fix" code which isn't really broken, I chose to
disable an unhelpful warning.

Signed-off-by: Richard W.M. Jones <rjones@redhat.com>