src/get.c: Disable false GCC warning
GCC 14.2.1 doesn't seem to be able to analyze this stack frame code
correctly.  When compiling augeas with --enable-compile-warnings=error
that causes the build to fail with the errors below.  Disable the
error around this code.

In file included from /usr/include/string.h:548,
                 from ../gnulib/lib/string.h:41,
                 from internal.h:31,
                 from get.c:30:
In function ‘memset’,
    inlined from ‘push_frame’ at get.c:1095:5:
/usr/include/bits/string_fortified.h:59:10: error: ‘__builtin_memset’ offset [0, 31] is out of the bounds [0, 0] [-Werror=array-bounds=]
   59 |   return __builtin___memset_chk (__dest, __ch, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   60 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~

If you disable -Warray-bounds only then you get this instead:

In file included from /usr/include/string.h:548,
                 from ../gnulib/lib/string.h:41,
                 from internal.h:31,
                 from get.c:30:
In function ‘memset’,
    inlined from ‘push_frame’ at get.c:1100:5:
/usr/include/bits/string_fortified.h:59:10: error: ‘__builtin_memset’ writing 32 bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
   59 |   return __builtin___memset_chk (__dest, __ch, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   60 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘push_frame’:
cc1: note: destination object is likely at address zero

Signed-off-by: Richard W.M. Jones <rjones@redhat.com>