src/augtool: fix multiple definition of xasprintf
`xasprintf` is defined both in *internal.c* and *augtool.c*. This
breaks building augeas statically:

```
./.libs/libaugeas.a(internal.o): In function `xasprintf':
internal.c:(.text+0x934): multiple definition of `xasprintf'
augtool.o:augtool.c:(.text+0x8a4): first defined here
collect2: error: ld returned 1 exit status
```

Mark the definition of xasprintf in *augtool.c* as a private copy by
prefixing the function name with an underscore and making the function
static.