Miscellaneous GCC 16 fixes (#881)
* src/augprint.c: Comment out unused variable

augprint.c: In function ‘quote_value’:
augprint.c:1254:7: error: variable ‘has_special’ set but not used [-Werror=unused-but-set-variable=]
 1254 |   int has_special=0;
      |       ^~~~~~~~~~~

* src: Fix const-correctness for strchr and similar

GCC 16 passes the constness of the parameter through strchr/strrchr.
This commit fixes many problems of this kind:

augtool.c: In function ‘readline_path_generator’:
augtool.c:105:17: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  105 |     char *end = strrchr(text, SEP);
      |                 ^~~~~~~

* src/jmt.c: Comment out unused variables

jmt.c: In function 'collect':
jmt.c:1539:19: error: variable 'removed' set but not used [-Werror=unused-but-set-variable=]
 1539 |     size_t count, removed;
      |                   ^~~~~~~
jmt.c:1539:12: error: variable 'count' set but not used [-Werror=unused-but-set-variable=]
 1539 |     size_t count, removed;
      |            ^~~~~

* tests/test-run.c: Comment out unused variable

test-run.c: In function ‘read_tests’:
test-run.c:132:9: error: variable ‘lc’ set but not used [-Werror=unused-but-set-variable=]
  132 |     int lc = 0;
      |         ^~